PROMPT DROP TABLE ARCHIVE_LOG;
DROP TABLE CANAL_PLUS.ARCHIVE_LOG CASCADE CONSTRAINTS;

PROMPT TABLE ARCHIVE_LOG;
--
-- ARCHIVE_LOG  (Table)
--

CREATE TABLE CANAL_PLUS.ARCHIVE_LOG
(
   archive_id       NUMBER NOT NULL,
   ARCHIVE_LOG_ID   NUMBER NOT NULL,
   MESSAGE_TYPE     VARCHAR2 (30 BYTE) NOT NULL,
   LOG_MESSAGE      VARCHAR2 (4000 BYTE) NOT NULL,
   CREATED_BY       VARCHAR2 (30 BYTE) NOT NULL,
   CREATED_TS       TIMESTAMP (6) DEFAULT SYSTIMESTAMP NOT NULL
)
TABLESPACE tables1;

ALTER TABLE ARCHIVE_LOG
   ADD CONSTRAINT ARCHIVE_LOG_PK PRIMARY KEY (ARCHIVE_LOG_ID)
       USING INDEX TABLESPACE index1;

ALTER TABLE ARCHIVE_LOG
   ADD CONSTRAINT ARCHIVE_LOG_CHECK CHECK
          (LOWER (MESSAGE_TYPE) IN ('info', 'warn', 'error'));