DROP TABLE CANAL_PLUS.ARCHIVE_POLICY_TABLES;

CREATE TABLE CANAL_PLUS.ARCHIVE_POLICY_TABLES
(
   POLICY_NAME   VARCHAR2 (50 BYTE) NOT NULL,
   TABLE_OWNER   VARCHAR2 (30) NOT NULL,
   TABLE_NAME    VARCHAR2 (30) NOT NULL,
   CONSTRAINT APT_POLICY_FK FOREIGN KEY (POLICY_NAME)
   REFERENCES ARCHIVE_POLICY (POLICY_NAME)
)
TABLESPACE TABLES1;

INSERT INTO ARCHIVE_POLICY_TABLES
     VALUES ('MERCHANT_DATA', 'CANAL_PLUS', 'MERCH_BAL');

INSERT INTO ARCHIVE_POLICY_TABLES
     VALUES ('MERCHANT_DATA', 'CANAL_PLUS', 'MERCH_BAL_WALLET');

INSERT INTO ARCHIVE_POLICY_TABLES
     VALUES ('MESSAGE_DATA', 'CANAL_PLUS', 'EMAIL_MESSAGE');

INSERT INTO ARCHIVE_POLICY_TABLES
     VALUES ('MESSAGE_DATA', 'CANAL_PLUS', 'SMS_MESSAGE');

INSERT INTO ARCHIVE_POLICY_TABLES
     VALUES ('MESSAGE_DATA', 'CANAL_PLUS', 'SMS_LOG');

INSERT INTO ARCHIVE_POLICY_TABLES
     VALUES ('MESSAGE_DATA', 'CANAL_PLUS', 'AUDIT_TRAIL');

INSERT INTO ARCHIVE_POLICY_TABLES
     VALUES ('MESSAGE_DATA', 'CANAL_PLUS', 'MERCHANT_MSG');

INSERT INTO ARCHIVE_POLICY_TABLES
     VALUES ('TXN_DATA', 'CANAL_PLUS', 'BILL_TXN');

INSERT INTO ARCHIVE_POLICY_TABLES
     VALUES ('TXN_DATA', 'CANAL_PLUS', 'BILL_TXN_AML');

INSERT INTO ARCHIVE_POLICY_TABLES
     VALUES ('TXN_DATA', 'CANAL_PLUS', 'BILL_TXN_DETAIL');

INSERT INTO ARCHIVE_POLICY_TABLES
     VALUES ('TXN_DATA', 'CANAL_PLUS', 'BILL_TXN_COMMISSION');

INSERT INTO ARCHIVE_POLICY_TABLES
     VALUES ('TXN_DATA', 'CANAL_PLUS', 'BILL_TXN_TAX');

INSERT INTO ARCHIVE_POLICY_TABLES
     VALUES ('TXN_DATA', 'CANAL_PLUS', 'BILL_TXN_FAILURE');

INSERT INTO ARCHIVE_POLICY_TABLES
     VALUES ('TXN_DATA', 'CANAL_PLUS', 'BILL_TXN_FEE');

INSERT INTO ARCHIVE_POLICY_TABLES
     VALUES ('TXN_DATA', 'CANAL_PLUS', 'BILL_TXN_PROP');

INSERT INTO ARCHIVE_POLICY_TABLES
     VALUES ('TXN_DATA', 'CANAL_PLUS', 'SVA_SUBTXN');

INSERT INTO ARCHIVE_POLICY_TABLES
     VALUES ('TXN_DATA', 'CANAL_PLUS', 'EVOUCHER_INFO');

INSERT INTO ARCHIVE_POLICY_TABLES
     VALUES ('TXN_DATA', 'CANAL_PLUS', 'EXTERNAL_SYSTEM_BI');

INSERT INTO ARCHIVE_POLICY_TABLES
     VALUES ('TXN_DATA', 'CANAL_PLUS', 'CREDIT_APPROVAL_HISTORY');

INSERT INTO ARCHIVE_POLICY_TABLES
     VALUES ('TOPUP_DATA', 'CANAL_PLUS', 'AUTH_TN');

INSERT INTO ARCHIVE_POLICY_TABLES
     VALUES ('TOPUP_DATA', 'CANAL_PLUS', 'AUTH_TXN_FAILURE');





--INSERT INTO ARCHIVE_policy_tables VALUES ('TXN_DATA', 'CANAL_PLUS', 'BILL_TXN_COMMISSION');

--INSERT INTO ARCHIVE_policy_tables VALUES ('TXN_DATA', 'CANAL_PLUS', 'BILL_TXN_FUNDOUT');

-- INSERT INTO ARCHIVE_policy_tables     VALUES ('TXN_DATA', 'CANAL_PLUS', 'BANK_SUBTXN');

-- INSERT INTO ARCHIVE_policy_tables  VALUES ('TXN_DATA', 'CANAL_PLUS', 'CARD_SUBTXN');


ALTER TABLE ARCHIVE_POLICY_TABLES
   ADD (ARCHIVE_TABLE_OWNER VARCHAR2 (30));

UPDATE ARCHIVE_POLICY_TABLES
   SET                                      --archive_table_name = table_name,
      ARCHIVE_TABLE_OWNER = 'CANAL_PLUS_ARCH'
 WHERE POLICY_NAME != 'REPORT_DATA';

COMMIT;
