-- 3 mins

CREATE INDEX OTAR_OT_PROD.IDX_TOPUP_INFO_TRUNC_REQ_TS
   ON OTAR_OT_PROD.TOPUP_INFO (TRUNC (REQUEST_TIMESTAMP))
   TABLESPACE index1
   PARALLEL (DEGREE 8)
   NOLOGGING
   LOCAL;

ALTER INDEX OTAR_OT_PROD.IDX_TOPUP_INFO_TRUNC_REQ_TS
   NOPARALLEL
   LOGGING;

-- 6 mins

CREATE INDEX OTAR_OT_PROD.IDX_SMS_MESSAGE_TRUNC_TS
   ON OTAR_OT_PROD.SMS_MESSAGE (TRUNC (timestamp))
   TABLESPACE index1
   PARALLEL (DEGREE 8)
   NOLOGGING
   LOCAL
   INITRANS 15;

ALTER INDEX OTAR_OT_PROD.IDX_SMS_MESSAGE_TRUNC_TS
   NOPARALLEL
   LOGGING;