PROMPT DROP TABLE ARCHIVE_CONTROL;
DROP TABLE CANAL_PLUS.ARCHIVE_CONTROL CASCADE CONSTRAINTS;

PROMPT TABLE ARCHIVE_CONTROL;
--
-- ARCHIVE_CONTROL  (Table)
--

CREATE TABLE CANAL_PLUS.ARCHIVE_CONTROL
(
   stop_archive_process   CHAR (1) NOT NULL,
   CREATED_BY             VARCHAR2 (30 BYTE) NOT NULL,
   CREATED_TS             TIMESTAMP (6) DEFAULT SYSTIMESTAMP NOT NULL
)
TABLESPACE tables1;

INSERT INTO archive_control
     VALUES ('F', USER, SYSDATE);

COMMIT;