Prompt drop TABLE MERCHANT_SESSION;
ALTER TABLE MERCHANT_SESSION
 DROP PRIMARY KEY CASCADE
/

DROP TABLE MERCHANT_SESSION CASCADE CONSTRAINTS
/

Prompt Table MERCHANT_SESSION;
--
-- MERCHANT_SESSION  (Table) 
--
CREATE TABLE MERCHANT_SESSION
(
  ID          VARCHAR2(64 BYTE)                 NOT NULL,
  SESSION_ID  VARCHAR2(64 BYTE)                 NOT NULL,
  CREATED     DATE                              NOT NULL,
  LAST_USE    DATE                              NOT NULL,
  VERSION     NUMBER(18)                        NOT NULL
) TABLESPACE tables_arch
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


Prompt Index IDX_MERCHANT_SESSION_PK;
--
-- IDX_MERCHANT_SESSION_PK  (Index) 
--
CREATE UNIQUE INDEX IDX_MERCHANT_SESSION_PK ON MERCHANT_SESSION
(ID)
LOGGING
NOPARALLEL
/


-- 
-- Non Foreign Key Constraints for Table MERCHANT_SESSION 
-- 
Prompt Non-Foreign Key Constraints on Table MERCHANT_SESSION;
ALTER TABLE MERCHANT_SESSION ADD (
  CONSTRAINT IDX_MERCHANT_SESSION_PK
  PRIMARY KEY
  (ID)
  USING INDEX IDX_MERCHANT_SESSION_PK
  ENABLE VALIDATE)
/

-- 
-- Foreign Key Constraints for Table MERCHANT_SESSION 
-- 
Prompt Foreign Key Constraints on Table MERCHANT_SESSION;
ALTER TABLE MERCHANT_SESSION ADD (
  CONSTRAINT IDX_MERCHANT_SESSION_FK 
  FOREIGN KEY (ID) 
  REFERENCES MERCHANT (ID)
  ENABLE NOVALIDATE)
/
