Prompt drop TABLE SMS_LOG;
ALTER TABLE SMS_LOG
 DROP PRIMARY KEY CASCADE
/

DROP TABLE SMS_LOG CASCADE CONSTRAINTS
/

Prompt Table SMS_LOG;
--
-- SMS_LOG  (Table) 
--
CREATE TABLE SMS_LOG
(
  ID          NUMBER                            NOT NULL,
  SMSC        VARCHAR2(16 BYTE)                 NOT NULL,
  SUB_NUMBER  VARCHAR2(32 BYTE)                 NOT NULL,
  TIMESTAMP   DATE                              NOT NULL,
  VERSION     NUMBER(18)
) TABLESPACE tables_arch
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


Prompt Index IDX_SMS_LOG_PK;
--
-- IDX_SMS_LOG_PK  (Index) 
--
CREATE UNIQUE INDEX IDX_SMS_LOG_PK ON SMS_LOG
(ID)
LOGGING
NOPARALLEL
/


Prompt Index IDX_SMS_LOG_TIMESTAMP;
--
-- IDX_SMS_LOG_TIMESTAMP  (Index) 
--
CREATE INDEX IDX_SMS_LOG_TIMESTAMP ON SMS_LOG
(TIMESTAMP)
LOGGING
NOPARALLEL
/


Prompt Index IDX_SMS_LOG_SMSC;
--
-- IDX_SMS_LOG_SMSC  (Index) 
--
CREATE INDEX IDX_SMS_LOG_SMSC ON SMS_LOG
(SMSC)
LOGGING
NOPARALLEL
/


-- 
-- Non Foreign Key Constraints for Table SMS_LOG 
-- 
Prompt Non-Foreign Key Constraints on Table SMS_LOG;
ALTER TABLE SMS_LOG ADD (
  CONSTRAINT IDX_SMS_LOG_PK
  PRIMARY KEY
  (ID)
  USING INDEX IDX_SMS_LOG_PK
  ENABLE VALIDATE)
/
