Prompt drop TABLE SMS_MESSAGE_AUDIT;
DROP TABLE SMS_MESSAGE_AUDIT CASCADE CONSTRAINTS
/

Prompt Table SMS_MESSAGE_AUDIT;
--
-- SMS_MESSAGE_AUDIT  (Table) 
--
CREATE TABLE SMS_MESSAGE_AUDIT
(
  AUDIT_ID         NUMBER                       NOT NULL,
  AUDIT_MESSAGE    VARCHAR2(64 BYTE)            NOT NULL,
  AUDIT_USER_ID    VARCHAR2(64 BYTE)            NOT NULL,
  AUDIT_TIMESTAMP  TIMESTAMP(6)                 NOT NULL,
  AUDIT_FREE_TEXT  VARCHAR2(256 BYTE),
  AUDIT_VERSION    NUMBER(18)                   DEFAULT 0,
  ID               NUMBER                       NOT NULL,
  TXN_ID           INTEGER,
  SUB_NUMBER       VARCHAR2(32 BYTE)            NOT NULL,
  MESSAGE          VARCHAR2(480 BYTE)           NOT NULL,
  TIMESTAMP        DATE                         NOT NULL,
  VERSION          NUMBER(18)
) TABLESPACE tables_arch
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/
