Prompt drop TABLE BILL_TXN_DETAIL;
ALTER TABLE BILL_TXN_DETAIL
 DROP PRIMARY KEY CASCADE
/

DROP TABLE BILL_TXN_DETAIL CASCADE CONSTRAINTS
/

Prompt Table BILL_TXN_DETAIL;
--
-- BILL_TXN_DETAIL  (Table) 
--
CREATE TABLE BILL_TXN_DETAIL
(
  ID                   NUMBER(38)               NOT NULL,
  TXN_ID               NUMBER(38)               NOT NULL,
  REGION_ID            VARCHAR2(32 BYTE)        NOT NULL,
  BU_ID                VARCHAR2(32 BYTE)        NOT NULL,
  COUNTRY_ID           VARCHAR2(20 BYTE)        NOT NULL,
  LANG_ID              VARCHAR2(20 BYTE)        NOT NULL,
  RESERVED_1           VARCHAR2(32 BYTE),
  RESERVED_2           VARCHAR2(32 BYTE),
  VERSION              NUMBER(18)               DEFAULT 0                     NOT NULL,
  FK_TZ_ID             NUMBER(12),
  TYPE                 VARCHAR2(20 BYTE)        NOT NULL,
  PRICE                NUMBER(18,6)             NOT NULL,
  REPORTING_SEQ        NUMBER(3)                NOT NULL,
  REPORTING_TIMESTAMP  DATE                     NOT NULL,
  REPORTING_STATUS     VARCHAR2(30 BYTE)        NOT NULL,
  REPORTING_FLAGS      NUMBER(18)               NOT NULL,
  MAX_SEQ              NUMBER(3)                NOT NULL,
  MAX_TIMESTAMP        DATE                     NOT NULL,
  MAX_STATUS           VARCHAR2(30 BYTE)        NOT NULL,
  MAX_FLAGS            NUMBER(18)               NOT NULL
) TABLESPACE tables_arch
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


Prompt Index IDX_BILL_TXN_DETAIL_TYPE;
--
-- IDX_BILL_TXN_DETAIL_TYPE  (Index) 
--
CREATE INDEX IDX_BILL_TXN_DETAIL_TYPE ON BILL_TXN_DETAIL
(TYPE)
LOGGING
NOPARALLEL
/


Prompt Index IDX_BILL_TXN_DETAIL_REPORTING;
--
-- IDX_BILL_TXN_DETAIL_REPORTING  (Index) 
--
CREATE INDEX IDX_BILL_TXN_DETAIL_REPORTING ON BILL_TXN_DETAIL
(REPORTING_TIMESTAMP, REPORTING_STATUS, TYPE)
LOGGING
NOPARALLEL
/


Prompt Index IDX_BILL_TXN_DETAIL_REPORTTS;
--
-- IDX_BILL_TXN_DETAIL_REPORTTS  (Index) 
--
CREATE INDEX IDX_BILL_TXN_DETAIL_REPORTTS ON BILL_TXN_DETAIL
(REPORTING_TIMESTAMP)
LOGGING
NOPARALLEL
/


Prompt Index IDX_BILL_TXN_DETAIL_MAX;
--
-- IDX_BILL_TXN_DETAIL_MAX  (Index) 
--
CREATE INDEX IDX_BILL_TXN_DETAIL_MAX ON BILL_TXN_DETAIL
(MAX_TIMESTAMP, MAX_STATUS, TYPE)
LOGGING
NOPARALLEL
/


Prompt Index IDX_BILL_TXN_DETAIL_MAXTS;
--
-- IDX_BILL_TXN_DETAIL_MAXTS  (Index) 
--
CREATE INDEX IDX_BILL_TXN_DETAIL_MAXTS ON BILL_TXN_DETAIL
(MAX_TIMESTAMP)
LOGGING
NOPARALLEL
/


Prompt Index UNQ_BTD_TXN_ID;
--
-- UNQ_BTD_TXN_ID  (Index) 
--
CREATE UNIQUE INDEX UNQ_BTD_TXN_ID ON BILL_TXN_DETAIL
(TXN_ID)
LOGGING
NOPARALLEL
/


Prompt Index IDX_BILL_TXN_DETAIL_REGION;
--
-- IDX_BILL_TXN_DETAIL_REGION  (Index) 
--
CREATE INDEX IDX_BILL_TXN_DETAIL_REGION ON BILL_TXN_DETAIL
(REGION_ID)
LOGGING
NOPARALLEL
/


Prompt Index IDX_BILL_TXN_DETAIL_BU;
--
-- IDX_BILL_TXN_DETAIL_BU  (Index) 
--
CREATE INDEX IDX_BILL_TXN_DETAIL_BU ON BILL_TXN_DETAIL
(BU_ID)
LOGGING
NOPARALLEL
/


Prompt Index IDX_BILL_TXN_DETAIL_REPSEQ;
--
-- IDX_BILL_TXN_DETAIL_REPSEQ  (Index) 
--
CREATE INDEX IDX_BILL_TXN_DETAIL_REPSEQ ON BILL_TXN_DETAIL
(REPORTING_SEQ)
LOGGING
NOPARALLEL
/


Prompt Index IDX_BILL_TXN_DETAIL_REPSEQTXN;
--
-- IDX_BILL_TXN_DETAIL_REPSEQTXN  (Index) 
--
CREATE INDEX IDX_BILL_TXN_DETAIL_REPSEQTXN ON BILL_TXN_DETAIL
(TXN_ID, REPORTING_SEQ)
LOGGING
NOPARALLEL
/


Prompt Index PK_BILL_TXN_ID;
--
-- PK_BILL_TXN_ID  (Index) 
--
CREATE UNIQUE INDEX PK_BILL_TXN_ID ON BILL_TXN_DETAIL
(ID)
LOGGING
NOPARALLEL
/


Prompt Index IDX_BILL_TXN_DETAIL_REGBU;
--
-- IDX_BILL_TXN_DETAIL_REGBU  (Index) 
--
CREATE INDEX IDX_BILL_TXN_DETAIL_REGBU ON BILL_TXN_DETAIL
(REGION_ID, BU_ID)
LOGGING
NOPARALLEL
/


-- 
-- Non Foreign Key Constraints for Table BILL_TXN_DETAIL 
-- 
Prompt Non-Foreign Key Constraints on Table BILL_TXN_DETAIL;
ALTER TABLE BILL_TXN_DETAIL ADD (
  CONSTRAINT PK_BILL_TXN_ID
  PRIMARY KEY
  (ID)
  USING INDEX PK_BILL_TXN_ID
  ENABLE VALIDATE,
  CONSTRAINT UNQ_BTD_TXN_ID
  UNIQUE (TXN_ID)
  USING INDEX UNQ_BTD_TXN_ID
  ENABLE VALIDATE)
/

-- 
-- Foreign Key Constraints for Table BILL_TXN_DETAIL 
-- 
Prompt Foreign Key Constraints on Table BILL_TXN_DETAIL;
ALTER TABLE BILL_TXN_DETAIL ADD (
  CONSTRAINT FK_BILLTXN_DETAIL_TZID 
  FOREIGN KEY (FK_TZ_ID) 
  REFERENCES TIME_ZONE (ID)
  ENABLE VALIDATE,
  CONSTRAINT FK_BTD_BU_ID 
  FOREIGN KEY (BU_ID) 
  REFERENCES BUSINESS_UNIT (BU_ID)
  ENABLE VALIDATE,
  CONSTRAINT FK_BTD_C_ID 
  FOREIGN KEY (COUNTRY_ID) 
  REFERENCES COUNTRY (COUNTRY_ID)
  ENABLE VALIDATE,
  CONSTRAINT FK_BTD_REG_ID 
  FOREIGN KEY (REGION_ID) 
  REFERENCES REGION (REGION_ID)
  ENABLE VALIDATE)
/
