Prompt drop TABLE EVOUCHER_INFO;
ALTER TABLE EVOUCHER_INFO
 DROP PRIMARY KEY CASCADE
/

DROP TABLE EVOUCHER_INFO CASCADE CONSTRAINTS
/

Prompt Table EVOUCHER_INFO;
--
-- EVOUCHER_INFO  (Table) 
--
CREATE TABLE EVOUCHER_INFO
(
  ID               NUMBER(18)                   NOT NULL,
  STATUS           VARCHAR2(20 BYTE)            NOT NULL,
  TXN_ID           NUMBER(38)                   NOT NULL,
  FK_MERCHANT_ID   VARCHAR2(64 BYTE)            NOT NULL,
  FK_COUNTRY_ID    VARCHAR2(20 BYTE)            NOT NULL,
  FK_CURRENCY_ID   VARCHAR2(20 BYTE)            NOT NULL,
  PRICE            NUMBER(18,6)                 NOT NULL,
  FORMULA          VARCHAR2(100 BYTE),
  DURATION         VARCHAR2(50 BYTE),
  OPTIONS          VARCHAR2(50 BYTE),
  PRODUCT_ID       VARCHAR2(20 BYTE)            NOT NULL,
  VOUCHER_NUMBER   VARCHAR2(16 BYTE)            NOT NULL,
  EXPIRATION_DATE  VARCHAR2(20 BYTE)            NOT NULL,
  TIME_STAMP       TIMESTAMP(6)                 NOT NULL
) TABLESPACE tables_arch
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


--  There is no statement for index CANAL_TUNE.SYS_C0014072.
--  The object is created when the parent object is created.

Prompt Index UNQ_VOUCHER_NUMBER;
--
-- UNQ_VOUCHER_NUMBER  (Index) 
--
CREATE UNIQUE INDEX UNQ_VOUCHER_NUMBER ON EVOUCHER_INFO
(VOUCHER_NUMBER)
LOGGING
NOPARALLEL
/


-- 
-- Non Foreign Key Constraints for Table EVOUCHER_INFO 
-- 
Prompt Non-Foreign Key Constraints on Table EVOUCHER_INFO;
ALTER TABLE EVOUCHER_INFO ADD (
  PRIMARY KEY
  (ID)
  ENABLE VALIDATE,
  CONSTRAINT UNQ_VOUCHER_NUMBER
  UNIQUE (VOUCHER_NUMBER)
  USING INDEX UNQ_VOUCHER_NUMBER
  ENABLE VALIDATE)
/

-- 
-- Foreign Key Constraints for Table EVOUCHER_INFO 
-- 
Prompt Foreign Key Constraints on Table EVOUCHER_INFO;
ALTER TABLE EVOUCHER_INFO ADD (
  FOREIGN KEY (FK_CURRENCY_ID) 
  REFERENCES CURRENCY (CUR_ID)
  ENABLE VALIDATE,
  FOREIGN KEY (FK_COUNTRY_ID) 
  REFERENCES COUNTRY (COUNTRY_ID)
  ENABLE VALIDATE,
  FOREIGN KEY (FK_MERCHANT_ID) 
  REFERENCES MERCHANT (ID)
  ENABLE VALIDATE)
/
