Prompt drop TABLE SMS_MESSAGE;
ALTER TABLE SMS_MESSAGE
 DROP PRIMARY KEY CASCADE
/

DROP TABLE SMS_MESSAGE CASCADE CONSTRAINTS
/

Prompt Table SMS_MESSAGE;
--
-- SMS_MESSAGE  (Table) 
--
CREATE TABLE SMS_MESSAGE
(
  ID          NUMBER                            NOT NULL,
  TXN_ID      INTEGER,
  SUB_NUMBER  VARCHAR2(32 BYTE)                 NOT NULL,
  MESSAGE     VARCHAR2(480 BYTE)                NOT NULL,
  TIMESTAMP   DATE                              NOT NULL,
  VERSION     NUMBER(18)
) TABLESPACE tables_arch
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


Prompt Index IDX_SMS_MESSAGE_PK;
--
-- IDX_SMS_MESSAGE_PK  (Index) 
--
CREATE UNIQUE INDEX IDX_SMS_MESSAGE_PK ON SMS_MESSAGE
(ID)
LOGGING
NOPARALLEL
/


Prompt Index IDX_SMS_MESSAGE_SUB_NUMBER;
--
-- IDX_SMS_MESSAGE_SUB_NUMBER  (Index) 
--
CREATE INDEX IDX_SMS_MESSAGE_SUB_NUMBER ON SMS_MESSAGE
(SUB_NUMBER)
LOGGING
NOPARALLEL
/


Prompt Index IDX_SMS_MESSAGE_TXN_ID;
--
-- IDX_SMS_MESSAGE_TXN_ID  (Index) 
--
CREATE INDEX IDX_SMS_MESSAGE_TXN_ID ON SMS_MESSAGE
(TXN_ID)
LOGGING
NOPARALLEL
/


-- 
-- Non Foreign Key Constraints for Table SMS_MESSAGE 
-- 
Prompt Non-Foreign Key Constraints on Table SMS_MESSAGE;
ALTER TABLE SMS_MESSAGE ADD (
  CONSTRAINT IDX_SMS_MESSAGE_PK
  PRIMARY KEY
  (ID)
  USING INDEX IDX_SMS_MESSAGE_PK
  ENABLE VALIDATE)
/
