Prompt drop TABLE BILL_TXN;
ALTER TABLE BILL_TXN
 DROP PRIMARY KEY CASCADE
/

DROP TABLE BILL_TXN CASCADE CONSTRAINTS
/

Prompt Table BILL_TXN;
--
-- BILL_TXN  (Table) 
--
CREATE TABLE BILL_TXN
(
  TXN_ID               INTEGER,
  SEQ_ID               NUMBER(3),
  TIMESTAMP            TIMESTAMP(6)             NOT NULL,
  STATUS               VARCHAR2(30 BYTE)        NOT NULL,
  TYPE                 VARCHAR2(20 BYTE)        NOT NULL,
  SRC_ID               VARCHAR2(64 BYTE)        NOT NULL,
  SRC_TYPE             NUMBER(3)                NOT NULL,
  SRC_REF              VARCHAR2(64 BYTE),
  DEST_ID              VARCHAR2(64 BYTE),
  DEST_TYPE            NUMBER(3),
  PRICE                NUMBER(18,6),
  PRICE_CRNCY          VARCHAR2(3 BYTE),
  CHANNEL              VARCHAR2(16 BYTE)        NOT NULL,
  BILL_SRVC_ID         VARCHAR2(64 BYTE),
  REFERENCE            VARCHAR2(128 BYTE),
  PROD_ID              VARCHAR2(64 BYTE),
  TAX_NAME             VARCHAR2(20 BYTE),
  TAX_RATE             NUMBER(9,6),
  FEE                  NUMBER(18,6),
  FREETEXT             VARCHAR2(128 BYTE),
  MULTIMODE_SRC        VARCHAR2(64 BYTE),
  MULTIMODE_DEST       VARCHAR2(64 BYTE),
  VERSION              NUMBER(18),
  IP_ADDR              VARCHAR2(15 BYTE),
  FLAGS                NUMBER(18),
  ACCOUNTING_EVENT_ID  NUMBER(4)
) TABLESPACE tables_arch
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


Prompt Index IDX_BILL_TXN_SRC;
--
-- IDX_BILL_TXN_SRC  (Index) 
--
CREATE INDEX IDX_BILL_TXN_SRC ON BILL_TXN
(SRC_ID, SRC_TYPE) TABLESPACE indexes_arch
LOGGING
NOPARALLEL
/


Prompt Index IDX_BILL_TXN_DEST;
--
-- IDX_BILL_TXN_DEST  (Index) 
--
CREATE INDEX IDX_BILL_TXN_DEST ON BILL_TXN
(DEST_ID, DEST_TYPE) TABLESPACE indexes_arch
LOGGING
NOPARALLEL
/


Prompt Index IDX_BILL_TXN_STATUS_TYPE;
--
-- IDX_BILL_TXN_STATUS_TYPE  (Index) 
--
CREATE INDEX IDX_BILL_TXN_STATUS_TYPE ON BILL_TXN
(STATUS, TYPE) TABLESPACE indexes_arch
LOGGING
NOPARALLEL
/


Prompt Index IDX_BILL_TXN_4;
--
-- IDX_BILL_TXN_4  (Index) 
--
CREATE INDEX IDX_BILL_TXN_4 ON BILL_TXN
(DEST_ID, TYPE, STATUS, DEST_TYPE, TIMESTAMP, 
TXN_ID, SEQ_ID) TABLESPACE indexes_arch
LOGGING
NOPARALLEL
/


Prompt Index IDX_BILL_TXN_TIMESTAMP;
--
-- IDX_BILL_TXN_TIMESTAMP  (Index) 
--
CREATE INDEX IDX_BILL_TXN_TIMESTAMP ON BILL_TXN
(TIMESTAMP) TABLESPACE indexes_arch
LOGGING
NOPARALLEL
/


Prompt Index IDX_BILL_TXN_3;
--
-- IDX_BILL_TXN_3  (Index) 
--
CREATE INDEX IDX_BILL_TXN_3 ON BILL_TXN
(SRC_ID, TYPE, STATUS, SRC_TYPE, TIMESTAMP, 
TXN_ID, SEQ_ID) TABLESPACE indexes_arch
LOGGING
NOPARALLEL
/


Prompt Index IDX_BILL_TXN_PK;
--
-- IDX_BILL_TXN_PK  (Index) 
--
CREATE UNIQUE INDEX IDX_BILL_TXN_PK ON BILL_TXN
(TXN_ID, SEQ_ID) TABLESPACE indexes_arch
LOGGING
NOPARALLEL
/


-- 
-- Non Foreign Key Constraints for Table BILL_TXN 
-- 
Prompt Non-Foreign Key Constraints on Table BILL_TXN;
ALTER TABLE BILL_TXN ADD (
  CONSTRAINT IDX_BILL_TXN_PK
  PRIMARY KEY
  (TXN_ID, SEQ_ID) 
  USING INDEX IDX_BILL_TXN_PK
  ENABLE VALIDATE) 
/
