Prompt drop TABLE BILL_TXN_PROP;
ALTER TABLE BILL_TXN_PROP
 DROP PRIMARY KEY CASCADE
/

DROP TABLE BILL_TXN_PROP CASCADE CONSTRAINTS
/

Prompt Table BILL_TXN_PROP;
--
-- BILL_TXN_PROP  (Table) 
--
CREATE TABLE BILL_TXN_PROP
(
  TXN_ID      NUMBER                            NOT NULL,
  PROP_NAME   VARCHAR2(64 BYTE)                 NOT NULL,
  PROP_VALUE  VARCHAR2(256 BYTE)                NOT NULL,
  SEQ_ID      NUMBER(1)                         NOT NULL,
  VERSION     INTEGER
) TABLESPACE tables_arch
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


Prompt Index IDX_BILL_TXN_PROP_PK;
--
-- IDX_BILL_TXN_PROP_PK  (Index) 
--
CREATE UNIQUE INDEX IDX_BILL_TXN_PROP_PK ON BILL_TXN_PROP
(TXN_ID, PROP_NAME)
LOGGING
NOPARALLEL
/


-- 
-- Non Foreign Key Constraints for Table BILL_TXN_PROP 
-- 
Prompt Non-Foreign Key Constraints on Table BILL_TXN_PROP;
ALTER TABLE BILL_TXN_PROP ADD (
  CONSTRAINT IDX_BILL_TXN_PROP_PK
  PRIMARY KEY
  (TXN_ID, PROP_NAME)
  USING INDEX IDX_BILL_TXN_PROP_PK
  ENABLE VALIDATE)
/

-- 
-- Foreign Key Constraints for Table BILL_TXN_PROP 
-- 
Prompt Foreign Key Constraints on Table BILL_TXN_PROP;
ALTER TABLE BILL_TXN_PROP ADD (
  CONSTRAINT IDX_BILL_TXN_PROP_FK 
  FOREIGN KEY (TXN_ID, SEQ_ID) 
  REFERENCES BILL_TXN (TXN_ID,SEQ_ID)
  ENABLE NOVALIDATE)
/
