Prompt drop TABLE MERCHANT_TOKEN_AUDIT;
ALTER TABLE MERCHANT_TOKEN_AUDIT
 DROP PRIMARY KEY CASCADE
/

DROP TABLE MERCHANT_TOKEN_AUDIT CASCADE CONSTRAINTS
/

Prompt Table MERCHANT_TOKEN_AUDIT;
--
-- MERCHANT_TOKEN_AUDIT  (Table) 
--
CREATE TABLE MERCHANT_TOKEN_AUDIT
(
  ID               VARCHAR2(64 BYTE),
  TYPE             VARCHAR2(32 BYTE),
  VALUE            VARCHAR2(128 BYTE),
  EXPIRATION       DATE,
  VERSION          NUMBER(18),
  AUDIT_ID         NUMBER                       NOT NULL,
  AUDIT_MESSAGE    VARCHAR2(64 BYTE)            NOT NULL,
  AUDIT_USER_ID    VARCHAR2(64 BYTE)            NOT NULL,
  AUDIT_TIMESTAMP  TIMESTAMP(6)                 NOT NULL,
  AUDIT_FREETEXT   VARCHAR2(255 BYTE),
  AUDIT_VERSION    NUMBER(18)                   NOT NULL
) TABLESPACE tables_arch
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


Prompt Index IDX_MERCHANT_TOKEN_AUDIT_PK;
--
-- IDX_MERCHANT_TOKEN_AUDIT_PK  (Index) 
--
CREATE UNIQUE INDEX IDX_MERCHANT_TOKEN_AUDIT_PK ON MERCHANT_TOKEN_AUDIT
(AUDIT_ID)
LOGGING
NOPARALLEL
/


-- 
-- Non Foreign Key Constraints for Table MERCHANT_TOKEN_AUDIT 
-- 
Prompt Non-Foreign Key Constraints on Table MERCHANT_TOKEN_AUDIT;
ALTER TABLE MERCHANT_TOKEN_AUDIT ADD (
  CONSTRAINT IDX_MERCHANT_TOKEN_AUDIT_PK
  PRIMARY KEY
  (AUDIT_ID)
  USING INDEX IDX_MERCHANT_TOKEN_AUDIT_PK
  ENABLE VALIDATE)
/
