Prompt drop TABLE BILL_TXN_COMMISSION;
ALTER TABLE BILL_TXN_COMMISSION
 DROP PRIMARY KEY CASCADE
/

DROP TABLE BILL_TXN_COMMISSION_ARCH CASCADE CONSTRAINTS
/

Prompt Table BILL_TXN_COMMISSION;
--
-- BILL_TXN_COMMISSION  (Table) 
--
CREATE TABLE BILL_TXN_COMMISSION
(
  TXN_ID               INTEGER                  NOT NULL,
  SEQ_ID               NUMBER(3)                NOT NULL,
  SYSTEM               NUMBER(18,6),
  ACOMM                NUMBER(18,6),
  TMOBILE              NUMBER(18,6),
  TELEFONICA           NUMBER(18,6),
  VODAFONE             NUMBER(18,6),
  RB                   NUMBER(18,6),
  CSAS                 NUMBER(18,6),
  GE                   NUMBER(18,6),
  UCB                  NUMBER(18,6),
  SYSTEM_NOT_PAID      NUMBER(18,6),
  ACOMM_NOT_PAID       NUMBER(18,6),
  TMOBILE_NOT_PAID     NUMBER(18,6),
  TELEFONICA_NOT_PAID  NUMBER(18,6),
  VODAFONE_NOT_PAID    NUMBER(18,6),
  RB_NOT_PAID          NUMBER(18,6),
  CSAS_NOT_PAID        NUMBER(18,6),
  GE_NOT_PAID          NUMBER(18,6),
  UCB_NOT_PAID         NUMBER(18,6),
  VERSION              NUMBER(18)               NOT NULL
) TABLESPACE tables_arch
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


Prompt Index IDX_BILL_TXN_COMMISSION_PK;
--
-- IDX_BILL_TXN_COMMISSION_PK  (Index) 
--
CREATE UNIQUE INDEX IDX_BILL_TXN_COMMISSION_PK ON BILL_TXN_COMMISSION
(TXN_ID)
LOGGING
NOPARALLEL
/


-- 
-- Non Foreign Key Constraints for Table BILL_TXN_COMMISSION 
-- 
Prompt Non-Foreign Key Constraints on Table BILL_TXN_COMMISSION;
ALTER TABLE BILL_TXN_COMMISSION ADD (
  CONSTRAINT IDX_BILL_TXN_COMMISSION_PK
  PRIMARY KEY
  (TXN_ID)
  USING INDEX IDX_BILL_TXN_COMMISSION_PK
  ENABLE VALIDATE)
/

-- 
-- Foreign Key Constraints for Table BILL_TXN_COMMISSION 
-- 
Prompt Foreign Key Constraints on Table BILL_TXN_COMMISSION;
ALTER TABLE BILL_TXN_COMMISSION ADD (
  CONSTRAINT IDX_BILL_TXN_COMMISSION_FK 
  FOREIGN KEY (TXN_ID, SEQ_ID) 
  REFERENCES BILL_TXN (TXN_ID,SEQ_ID)
  ENABLE NOVALIDATE)
/
