Prompt drop TABLE MERCH_BAL;
ALTER TABLE MERCH_BAL
 DROP PRIMARY KEY CASCADE
/

DROP TABLE MERCH_BAL CASCADE CONSTRAINTS
/

Prompt Table MERCH_BAL;
--
-- MERCH_BAL  (Table) 
--
CREATE TABLE MERCH_BAL
(
  TIMESTAMP  DATE                               NOT NULL,
  ID         VARCHAR2(64 BYTE)                  NOT NULL,
  PARENT_ID  VARCHAR2(64 BYTE)                  NOT NULL,
  ROOT_ID    VARCHAR2(64 BYTE)                  NOT NULL,
  BALANCE    NUMBER(18,6)                       NOT NULL,
  TYPE       VARCHAR2(64 BYTE),
  VERSION    NUMBER(18),
  BANK_ID    NUMBER,
  CRNCY      VARCHAR2(3 BYTE)                   NOT NULL
) TABLESPACE tables_arch
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


Prompt Index IDX_MERCH_BAL_PK;
--
-- IDX_MERCH_BAL_PK  (Index) 
--
CREATE UNIQUE INDEX IDX_MERCH_BAL_PK ON MERCH_BAL
(TIMESTAMP, ID)
LOGGING
NOPARALLEL
/


-- 
-- Non Foreign Key Constraints for Table MERCH_BAL 
-- 
Prompt Non-Foreign Key Constraints on Table MERCH_BAL;
ALTER TABLE MERCH_BAL ADD (
  CONSTRAINT IDX_MERCH_BAL_PK
  PRIMARY KEY
  (TIMESTAMP, ID)
  USING INDEX IDX_MERCH_BAL_PK
  ENABLE VALIDATE)
/
